name:                sbv-playground
version:             0.1.0.0
license:             BSD3
author:              "Andrew Anderson"
copyright:           "2020 Andrew Anderson"

description:         A collection of examples using the sbv library

dependencies:
- base >= 4.7 && < 5

executables:
  sbv-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sbv
